input {

  udp {
    port => 514
    type => "cisco"
  }
}

filter {

  if [type] == "cisco" {

    grok {
      match => {
        "message" => "<%{INT:priority}>%{INT:sequence}: %{CISCOTIMESTAMP:log_timestamp} : %%{DATA:facility}-%{INT:severity}-%{DATA:mnemonic}: %{GREEDYDATA:message_text}"
      }
    }

    mutate {
      add_field => {
        "vendor" => "cisco"
      }
    }

    date {
      match => [ "log_timestamp", "MMM dd HH:mm:ss.SSS" ]
    }
  }
}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "${ES_LOCAL_PASSWORD}"
    index => "cisco-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}